version: '3.5'
services:
  web:
    build:
      context: ./
      dockerfile: .docker/web.docker
    volumes:
      - ./:/var/www
    ports:
      - '8884:80'
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: .docker/app.docker
    volumes:
      - ./:/var/www
    links:
      - database
      - cache
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=database'
      - 'REDIS_PORT=6379'
      - 'REDIS_HOST=cache'
  database:
    image: mysql:5.7.20
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode=""
    environment:
      - 'MYSQL_ROOT_PASSWORD=6k6BYsQ8f-8t8^7Y'
      - 'MYSQL_DATABASE=app'
    ports:
      - '3384:3306'
  cache:
    image: redis:4.0.6
    ports:
      - '6384:6379'
